// Generated by dia2code
#ifndef STATE__ELEMENT__H
#define STATE__ELEMENT__H


namespace state {
  class Element;
}

#include "TypeId.h"

namespace state {

  /// class Element - 
  class Element {
    // Attributes
  protected:
    int x     = 0;
    int y     = 0;
    // Operations
  public:
    Element ();
    ~Element ();
    TypeId getTypeId () const;
    bool isStatic () const;
    bool equals (const Element& other) const;
    // Setters and Getters
    int getX() const;
    void setX(int x);
    int getY() const;
    void setY(int y);
  };

};

#endif
