// Generated by dia2code
#ifndef STATE__ELEMENTALLOC__H
#define STATE__ELEMENTALLOC__H

#include <vector>

namespace state {
  class ElementTab;
}

#include "ElementTab.h"

namespace state {

  /// class ElementAlloc - 
  class ElementAlloc {
    // Attributes
  protected:
    ElementTab Layer;
    std::vector<int> Layer_int;
    // Operations
  public:
    ElementTab getLayer ();
    ElementAlloc ();
    // Setters and Getters
    void setLayer(const ElementTab& Layer);
    const std::vector<int>& getLayer_int() const;
    void setLayer_int(const std::vector<int>& Layer_int);
  };

};

#endif
