// Generated by dia2code
#ifndef STATE__ELEMENTALLOC__H
#define STATE__ELEMENTALLOC__H


namespace state {
  class Element;
}

namespace state {

  /// class ElementAlloc - 
  template <  class E,   typename ID>
  class ElementAlloc {
    // Attributes
  protected:
    ID id;
    // Operations
  public:
    ElementAlloc (ID id);
    Element* newInstance ();
    // Setters and Getters
    const ID& getId() const;
    void setId(const ID& id);
  };

};

#endif
