// Generated by dia2code
#ifndef STATE__ELEMENTFACTORY__H
#define STATE__ELEMENTFACTORY__H

#include <map>

namespace state {
  class Element;
  class AElementAlloc;
  class ElementFactory;
}

namespace state {

  /// class ElementFactory - 
  class ElementFactory {
    // Attributes
  public:
    std::map<char, AElementAlloc*> list;
    // Operations
  public:
    ~ElementFactory ();
    Element* newInstance (char id) const;
    void registerType (char id, AElementAlloc* a);
    static ElementFactory* createDefault ();
    // Setters and Getters
  };

};

#endif
