// Generated by dia2code
#ifndef STATE__ELEMENTALLOC__H
#define STATE__ELEMENTALLOC__H

#include <vector>

namespace state {
  class ElementTab;
}

#include "ElementTab.h"

namespace state {

  /// class ElementAlloc - 
  class ElementAlloc {
    // Associations
    // Attributes
  protected:
    ElementTab layer;
    std::vector<int> layerInt;
    // Operations
  public:
    ElementTab getLayer ();
    ElementAlloc ();
    // Setters and Getters
    void setLayer(const ElementTab& layer);
    const std::vector<int>& getLayerInt() const;
    void setLayerInt(const std::vector<int>& layerInt);
  };

};

#endif
