// Generated by dia2code
#ifndef STATE__FLOOR__H
#define STATE__FLOOR__H


namespace state {
  class Element;
  class StaticElement;
}

#include "FloorTypeId.h"
#include "TypeId.h"
#include "StaticElement.h"

namespace state {

  /// class Floor - 
  class Floor : public state::StaticElement {
    // Associations
    // Attributes
  protected:
    FloorTypeId nature;
    // Operations
  public:
    Floor (FloorTypeId id);
    bool isSpace () const;
    TypeId getTypeId () const;
    bool equals (const Element& other) const;
    // Setters and Getters
    FloorTypeId getNature() const;
    void setNature(FloorTypeId nature);
  };

};

#endif
