// Generated by dia2code
#ifndef STATE__FLOORTYPEID__H
#define STATE__FLOORTYPEID__H


namespace state {

  enum FloorTypeId {
    GROUND     = 1,
    GRASS     = 2,
    WATER     = 3
  };

};

#endif
