// Generated by dia2code
#ifndef STATE__FLOORTYPEID__H
#define STATE__FLOORTYPEID__H


namespace state {

  enum FloorTypeId {
    FULL     = 1,
    SLOPELEFT     = 2,
    SLOPERIGHT     = 3,
    LADDER     = 4
  };

};

#endif
