// Generated by dia2code
#ifndef STATE__LOADCSV__H
#define STATE__LOADCSV__H

#include <vector>
#include <string>

namespace state {

  /// class LoadCSV - 
  class LoadCSV {
    // Operations
  public:
    std::vector<int> loadCSV (std::string nom_fichier);
    // Setters and Getters
  };

};

#endif
