// Generated by dia2code
#ifndef STATE__OBSERVER__H
#define STATE__OBSERVER__H


namespace state {

  // interface
  /// class Observer - 
  class Observer {
    // Operations
  public:
    void notifier ();
    // Setters and Getters
  };

};

#endif
