// Generated by dia2code
#ifndef STATE__OBSERVABLE__H
#define STATE__OBSERVABLE__H

#include <vector>

namespace state {
  class Observer;
}

#include "Observer.h"

namespace state {

  /// class Observable - 
  class Observable {
    // Associations
    // Attributes
  private:
    std::vector<Observer*> observers;
    // Operations
  public:
    void ajouterObserver (Observer* o);
    void supprimerObserver (Observer* o);
    void notifierObserver ();
    // Setters and Getters
  };

};

#endif
