// Generated by dia2code
#ifndef STATE__PERSONNAGE__H
#define STATE__PERSONNAGE__H


namespace state {
  class MobileElement;
}

#include "Status.h"
#include "TypeId.h"
#include "MobileElement.h"

namespace state {

  /// class Personnage - 
  class Personnage : public state::MobileElement {
    // Attributes
  protected:
    int color;
    int Step     = 0;
    int Shoot     = 0;
    // Operations
  public:
    Personnage  (Status id);
    ~Personnage ();
    TypeId  getTypeId () const;
    // Setters and Getters
    int getColor() const;
    void setColor(int color);
    int getStep() const;
    void setStep(int Step);
    int getShoot() const;
    void setShoot(int Shoot);
  };

};

#endif
