// Generated by dia2code
#ifndef STATE__PERSONNAGE__H
#define STATE__PERSONNAGE__H


namespace state {
  class MobileElement;
}

#include "TypeId.h"
#include "MobileElement.h"

namespace state {

  /// class Personnage - 
  class Personnage : public state::MobileElement {
    // Attributes
  protected:
    int color;
    int step     = 0;
    int shoot     = 0;
    // Operations
  public:
    Personnage (int color);
    ~Personnage ();
    TypeId  getTypeId () const;
    bool isStatic () const;
    // Setters and Getters
    int getColor() const;
    void setColor(int color);
    int getStep() const;
    void setStep(int step);
    int getShoot() const;
    void setShoot(int shoot);
  };

};

#endif
