// Generated by dia2code
#ifndef STATE__SPACE__H
#define STATE__SPACE__H


namespace state {
  class Element;
  class StaticElement;
}

#include "SpaceTypeId.h"
#include "TypeId.h"
#include "StaticElement.h"

namespace state {

  /// class Space - 
  class Space : public state::StaticElement {
    // Associations
    // Attributes
  protected:
    SpaceTypeId nature;
    // Operations
  public:
    Space (SpaceTypeId id);
    bool isSpace () const;
    TypeId getTypeId () const;
    bool equals (const Element& other) const;
    // Setters and Getters
    SpaceTypeId getNature() const;
    void setNature(SpaceTypeId nature);
  };

};

#endif
