// Generated by dia2code
#ifndef STATE__SPACE__H
#define STATE__SPACE__H


namespace state {
  class StaticElement;
}

<<<<<<< HEAD
#include "SpaceTypeId.h"
=======
>>>>>>> 354a9cd21019c6cacb51d82aa3781ccb62ff8e6b
#include "TypeId.h"
#include "StaticElement.h"

namespace state {

  /// class Space - 
  class Space : public state::StaticElement {
    // Operations
  public:
    Space (SpaceTypeId id);
    bool isSpace () const;
    TypeId getTypeId () const;
<<<<<<< HEAD
    SpaceTypeId getSpaceTypeId () const;
    void setSpaceTypeId (SpaceTypeId id);
=======
>>>>>>> 354a9cd21019c6cacb51d82aa3781ccb62ff8e6b
    bool isStatic () const;
    // Setters and Getters
  };

};

#endif
