// Generated by dia2code
#ifndef STATE__STATE__H
#define STATE__STATE__H


namespace state {
  class ElementTab;
  class Observable;
}

#include "ElementTab.h"
#include "Observable.h"

namespace state {

  /// class State - 
  class State : public state::Observable {
    // Associations
    // Attributes
  private:
    ElementTab grid;
    ElementTab Chars;
  protected:
    int epoch     = 0;
    int epochrate     = 12;
    // Operations
  public:
    ElementTab& getGrid ();
    ElementTab& getChars ();
    // Setters and Getters
    int getEpoch() const;
    void setEpoch(int epoch);
    int getEpochrate() const;
    void setEpochrate(int epochrate);
  };

};

#endif
