// Generated by dia2code
#ifndef STATE__STATEEVENT__H
#define STATE__STATEEVENT__H


namespace state {
  class Event;
}

#include "StateEventId.h"
#include "EventTypeId.h"
#include "Event.h"

namespace state {

  /// class StateEvent - 
  class StateEvent : public state::Event {
    // Associations
    // Attributes
  public:
    StateEventId stateEvent;
    // Operations
  public:
    StateEvent (StateEventId se);
    EventTypeId getEventType () const;
    // Setters and Getters
  };

};

#endif
