// Generated by dia2code
#ifndef STATE__STATE__H
#define STATE__STATE__H


namespace state {
  class ElementTab;
}

#include "ElementTab.h"

namespace state {

  /// class State - 
  class State {
    // Attributes
  private:
    ElementTab grid;
    ElementTab chars;
  protected:
    int epoch     = 0;
    int epochrate     = 12;
    int stepcount     = 0;
    // Operations
  public:
    ElementTab& getGrid ();
    ElementTab& getChars ();
    // Setters and Getters
    int getEpoch() const;
    void setEpoch(int epoch);
    int getEpochrate() const;
    void setEpochrate(int epochrate);
    int getStepcount() const;
    void setStepcount(int stepcount);
  };

};

#endif
