// Generated by dia2code
#ifndef RENDER__LAYER__H
#define RENDER__LAYER__H

#include <memory>

namespace render {
  class TileMap;
  class TileSet;
}

#include "TileMap.h"
#include "TileSet.h"

namespace render {

  /// class Layer - 
  class Layer {
    // Attributes
  protected:
    std::unique_ptr<TileMap> tilemap;
    std::shared_ptr<TileSet> tileset;
    // Operations
  public:
    Layer ();
    ~Layer ();
    void setTileMap (TileMap* tilemap);
    void initTileMap ();
    // Setters and Getters
    const std::unique_ptr<TileMap>& getTilemap() const;
    void setTilemap(const std::unique_ptr<TileMap>& tilemap);
    const std::shared_ptr<TileSet>& getTileset() const;
    void setTileset(const std::shared_ptr<TileSet>& tileset);
  };

};

#endif
