// Generated by dia2code
#ifndef RENDER__STATELAYER__H
#define RENDER__STATELAYER__H

#include <SFML/Graphics.hpp>

namespace state {
  class State;
};
namespace sf {
  class Texture;
};
namespace render {
  class Layer;
}

#include "Layer.h"
#include "state/State.h"

namespace render {

  /// class StateLayer - 
  class StateLayer : public render::Layer {
    // Associations
    // Attributes
  private:
    state::State& state;
    sf::Texture m_texture;
    int lifeCount;
    // Operations
  public:
    StateLayer (state::State& state);
    void initSurface ();
    void printLifeCount ();
    // Setters and Getters
  };

};

#endif
