// Generated by dia2code
#ifndef RENDER__SURFACE__H
#define RENDER__SURFACE__H

#include <SFML/Graphics.hpp>
#include <string>

namespace sf {
  class Texture;
  class VertexArray;
};
namespace render {
  class Tile;
};
namespace sf {
  class Drawable;
  class Transformable;
};
namespace render {
  class Layer;
}

#include "Layer.h"

namespace render {

  /// class Surface - 
  class Surface : public sf::Drawable, public sf::Transformable {
    // Associations
    // Attributes
  private:
    sf::Texture texture;
    sf::VertexArray quads;
    sf::VertexArray triangles;
    // Operations
  public:
    void loadTexture (const std::string& image_file);
    void initQuads (int count);
    void initTriangles (int count);
    void setSpriteLocation (int i, int x, int y);
    void setSpriteTexture (int i, const Tile& tex);
    void draw (sf::RenderTarget& target, sf::RenderStates states) const;
    // Setters and Getters
  };

};

#endif
