// Generated by dia2code
#ifndef RENDER__TILESET__H
#define RENDER__TILESET__H

#include <string>

namespace render {
  class Tile;
};
namespace state {
  class Element;
};
namespace render {
  class Layer;
}

#include "state/Element.h"
#include "Tile.h"
#include "Layer.h"

namespace render {

  /// class TileSet - 
  class TileSet {
    // Associations
    // Operations
  public:
    virtual int getCellWidth () const = 0;
    virtual int getCellHeight () const = 0;
    virtual const std::string getImageFile () const = 0;
    virtual const Tile& getTile (const state::Element& e) const = 0;
    virtual const Tile& getCharTile (char c) const;
    // Setters and Getters
  };

};

#endif
