// Generated by dia2code
#ifndef RENDER__TILEMAP__H
#define RENDER__TILEMAP__H

#include <SFML/Graphics.hpp>
#include <string>
#include <vector>

namespace sf {
  class Texture;
  class VertexArray;
  class Drawable;
  class Transformable;
}


namespace render {

  /// class TileMap - 
  class TileMap : public sf::Drawable, public sf::Transformable {
    // Attributes
  private:
    sf::Texture texture;
    sf::VertexArray quads;
    // Operations
  public:
    void draw (sf::RenderTarget& target, sf::RenderStates states) const;
    bool load (const std::string&  tileset, sf::Vector2u tileSize, std::vector<int> tiles, unsigned int height, unsigned int width);
    // Setters and Getters
  };

};

#endif
