// Generated by dia2code
#ifndef AI__AI__H
#define AI__AI__H

#include <vector>

namespace engine {
  class Engine;
  class Command;
};
namespace state {
  class State;
  class Observer;
}

#include "state/Observer.h"
#include "engine/Engine.h"
#include "engine/Command.h"
#include "state/State.h"

namespace ai {

  /// class AI - 
  class AI : public state::Observer {
    // Operations
  public:
    virtual void run (engine::Engine& engine, int color) = 0;
  protected:
    void listCommands (std::vector<engine::Command*>& list, state::State& state, int color);
    // Setters and Getters
  };

};

#endif
