// Generated by dia2code
#ifndef AI__HEURISTICAI__H
#define AI__HEURISTICAI__H


namespace ai {
  class PathMap;
};
namespace state {
  class State;
};
namespace engine {
  class Engine;
};
namespace ai {
  class AI;
}

#include "PathMap.h"
#include "AI.h"

namespace ai {

  /// class HeuristicAI - 
  class HeuristicAI : public ai::AI {
    // Associations
    // Attributes
  private:
    PathMap lifeMap;
    PathMap ennemyMap;
    // Operations
  public:
    HeuristicAI (const state::State& state, int i, int j);
    const PathMap& getLifeMap () const;
    const PathMap& getEnnemyMap () const;
    void stateChanged (const state::Event& event);
    void run (engine::Engine& engine, int i, int j);
    bool dijkstra ();
    // Setters and Getters
  };

};

#endif
