// Generated by dia2code
#ifndef AI__PATHMAP__H
#define AI__PATHMAP__H

#include <vector>
#include <queue>

namespace ai {
  class Point;
};
namespace state {
  class ElementTab;
};
namespace ai {
  class PointCompareWeight;
}

#include "Point.h"
#include "state/ElementTab.h"
#include "PointCompareWeight.h"

namespace ai {

  /// class PathMap - 
  class PathMap {
    // Attributes
  private:
    int width     = 0;
    int height     = 0;
    std::vector<int> weights;
    std::priority_queue<Point, std::vector<Point>, PointCompareWeight> queue;
    // Operations
  public:
    int getWeight (const Point& p) const;
    void setWeight (const Point& p, int w);
    const std::vector<int> getWeights () const;
    void init (const state::ElementTab& grid);
    void addSink (Point p, int weight);
    void update (const state::ElementTab& grid);
    void setWeights (int indice, int valeur);
    // Setters and Getters
  };

};

#endif
