// Generated by dia2code
#ifndef ENGINE__ACTION__H
#define ENGINE__ACTION__H


namespace state {
  class State;
}

#include "ActionTypeId.h"

namespace engine {

  /// class Action - 
  class Action {
    // Operations
  public:
    virtual void apply (state::State& state) = 0;
    virtual void undo (state::State& state) = 0;
    virtual ActionTypeId getActionTypeId () const = 0;
    // Setters and Getters
  };

};

#endif
