// Generated by dia2code
#ifndef ENGINE__ACTIONTYPEID__H
#define ENGINE__ACTIONTYPEID__H


namespace engine {

  enum ActionTypeId {
    MOVE_ACTION     = 1,
    SHOOT_ACTION     = 2,
    LIFE_ACTION     = 3,
    KILL_ACTION     = 4
  };

};

#endif
