// Generated by dia2code
#ifndef ENGINE__COMMANDTYPEID__H
#define ENGINE__COMMANDTYPEID__H


namespace engine {

  enum CommandTypeId {
    MOVE_CHAR     = 1,
    ORIENTATION     = 2,
    HANDLE_LIFE     = 3,
    HANDLE_IMPACT     = 4
  };

};

#endif
