// Generated by dia2code
#ifndef ENGINE__ENGINE__H
#define ENGINE__ENGINE__H

#include <map>
#include <memory>

namespace state {
  class State;
};
namespace engine {
  class Command;
}

#include "state/State.h"

namespace engine {

  /// class Engine - 
  class Engine {
    // Attributes
  private:
    state::State currentState;
    std::map<int,std::unique_ptr<Command>> currentCommands;
    // Operations
  public:
    Engine ();
    ~Engine ();
     state::State& getState ();
    void addPassiveCommand ();
    void addCommand (int priority, Command* cmd);
    void update ();
    void moteur ();
    // Setters and Getters
  };

};

#endif
