// Generated by dia2code
#ifndef ENGINE__HANDLELIFESCOMMAND__H
#define ENGINE__HANDLELIFESCOMMAND__H


namespace state {
  class State;
};
namespace engine {
  class Command;
}

#include "state/SpaceTypeId.h"
#include "CommandTypeId.h"
#include "Command.h"

namespace engine {

  /// class HandleLifesCommand - 
  class HandleLifesCommand : public engine::Command {
    // Operations
  public:
    void takeLife (state::State& state, int pos, state::SpaceTypeId tyletype);
    void addLife (state::State& state);
    CommandTypeId getTypeId () const;
    void execute (state::State& state);
    // Setters and Getters
  };

};

#endif
