// Generated by dia2code
#ifndef ENGINE__HANDLEIMPACTCOMMAND__H
#define ENGINE__HANDLEIMPACTCOMMAND__H


namespace state {
  class State;
};
namespace engine {
  class Command;
}

#include "CommandTypeId.h"
#include "Command.h"
#include "state/Status.h"

namespace engine {

  /// class HandleImpactCommand - 
  class HandleImpactCommand : public engine::Command {
    // Operations
  public:
    void lostLife (state::State& state, int i, int j);
    void destruct (state::State& state, int i, int j);
    CommandTypeId getTypeId () const;
    void execute (state::State& state, int i, int j);
    // Setters and Getters
  };

};

#endif
