// Generated by dia2code
#ifndef ENGINE__JUMPCOMMAND__H
#define ENGINE__JUMPCOMMAND__H


namespace state {
  class State;
};
namespace engine {
  class Command;
}

#include "CommandTypeId.h"
#include "Command.h"

namespace engine {

  /// class JumpCommand - 
  class JumpCommand : public engine::Command {
    // Attributes
  protected:
    int i;
    int j;
    // Operations
  public:
    JumpCommand (int i, int j);
    CommandTypeId getTypeId () const;
    void execute (state::State& state);
    // Setters and Getters
    int getI() const;
    void setI(int i);
    int getJ() const;
    void setJ(int j);
  };

};

#endif
