// Generated by dia2code
#ifndef ENGINE__LIFEACTION__H
#define ENGINE__LIFEACTION__H


namespace state {
  class Personnage;
  class State;
};
namespace engine {
  class Action;
}

#include "Action.h"
#include "state/Personnage.h"

namespace engine {

  /// class LifeAction - 
  class LifeAction : public engine::Action {
    // Associations
    // Attributes
  protected:
    int color;
    int lifeCount;
    state::Personnage* persoApAction;
    // Operations
  public:
    LifeAction (int color, int lifeCount, state::Personnage* persoApAction);
    void apply (state::State& state);
    void undo (state::State& state);
    // Setters and Getters
    int getColor() const;
    void setColor(int color);
    int getLifeCount() const;
    void setLifeCount(int lifeCount);
    const state::Personnage*& getPersoApAction() const;
    void setPersoApAction(const state::Personnage*& persoApAction);
  };

};

#endif
