// Generated by dia2code
#ifndef ENGINE__MOVECHARACTION__H
#define ENGINE__MOVECHARACTION__H


namespace state {
  class Personnage;
  class State;
};
namespace engine {
  class Action;
}

#include "state/Direction.h"
#include "Action.h"
#include "state/Personnage.h"

namespace engine {

  /// class MoveCharAction - 
  class MoveCharAction : public engine::Action {
    // Associations
    // Attributes
  public:
    state::Direction nextDir;
  protected:
    int color;
    int xFrom;
    int yFrom;
    int xTo;
    int yTo;
    state::Personnage* persoApAction;
    state::Direction precDir;
    // Operations
  public:
    MoveCharAction (int color, int xFrom, int yFrom, int xTo, int yTo, state::Personnage* persoApAction, state::Direction precDir, state::Direction nextDir);
    void apply (state::State& state);
    void undo (state::State& state);
    // Setters and Getters
    int getColor() const;
    void setColor(int color);
    int getXFrom() const;
    void setXFrom(int xFrom);
    int getYFrom() const;
    void setYFrom(int yFrom);
    int getXTo() const;
    void setXTo(int xTo);
    int getYTo() const;
    void setYTo(int yTo);
    const state::Personnage*& getPersoApAction() const;
    void setPersoApAction(const state::Personnage*& persoApAction);
    state::Direction getPrecDir() const;
    void setPrecDir(state::Direction precDir);
  };

};

#endif
