// Generated by dia2code
#ifndef ENGINE__ORIENTATIONCOMMAND__H
#define ENGINE__ORIENTATIONCOMMAND__H


namespace state {
  class State;
};
namespace engine {
  class Command;
}

#include "state/Direction.h"
#include "CommandTypeId.h"
#include "Command.h"

namespace engine {

  /// class OrientationCommand - 
  class OrientationCommand : public engine::Command {
    // Attributes
  protected:
    int character;
    state:: Direction orientation;
    // Operations
  public:
    OrientationCommand (int c, state::Direction d);
    CommandTypeId getTypeId () const;
    void execute  (state::State& state);
    // Setters and Getters
    int getCharacter() const;
    void setCharacter(int character);
    const state:: Direction& getOrientation() const;
    void setOrientation(const state:: Direction& orientation);
  };

};

#endif
