// Generated by dia2code
#ifndef ENGINE__ORIENTATIONCOMMAND__H
#define ENGINE__ORIENTATIONCOMMAND__H


namespace state {
  class State;
};
namespace engine {
  class Command;
};
namespace state {
  class Personnage;
}

#include "state/Direction.h"
#include "CommandTypeId.h"
#include "Command.h"
#include "state/Personnage.h"

namespace engine {

  /// class OrientationCommand - 
  class OrientationCommand : public engine::Command {
    // Associations
    // Attributes
  protected:
    int character;
    state:: Direction orientation;
    int i;
    int j;
    // Operations
  public:
    OrientationCommand (int i, int j, state::Direction d);
    CommandTypeId getTypeId () const;
    void execute  (state::State& state);
    // Setters and Getters
    int getCharacter() const;
    void setCharacter(int character);
    const state:: Direction& getOrientation() const;
    void setOrientation(const state:: Direction& orientation);
    int getI() const;
    void setI(int i);
    int getJ() const;
    void setJ(int j);
  };

};

#endif
