// Generated by dia2code
#ifndef ENGINE__SHOOTCOMMAND__H
#define ENGINE__SHOOTCOMMAND__H

#include <stack>
#include <memory>

namespace state {
  class State;
};
namespace engine {
  class Action;
  class Command;
}

#include "CommandTypeId.h"
#include "Action.h"
#include "Command.h"

namespace engine {

  /// class ShootCommand - 
  class ShootCommand : public engine::Command {
    // Attributes
  protected:
    int color;
    // Operations
  public:
    ShootCommand (int color);
    CommandTypeId getTypeId () const;
    void execute (state::State& state, std::stack<std::shared_ptr<Action>>& actions);
    // Setters and Getters
    int getColor() const;
    void setColor(int color);
  };

};

#endif
