// Generated by dia2code
#ifndef ENGINE__SHOOTCOMMAND__H
#define ENGINE__SHOOTCOMMAND__H


namespace state {
  class State;
};
namespace engine {
  class Command;
}

#include "CommandTypeId.h"
#include "Command.h"

namespace engine {

  /// class ShootCommand - 
  class ShootCommand : public engine::Command {
    // Attributes
  protected:
    int color;
    // Operations
  public:
    ShootCommand (int color);
    CommandTypeId getTypeId () const;
    void execute (state::State& state);
    // Setters and Getters
    int getColor() const;
    void setColor(int color);
  };

};

#endif
