// Generated by dia2code
#ifndef ENGINE__TESTJSON__H
#define ENGINE__TESTJSON__H

#include <string>
#include <json/json.h>

namespace engine {
  class TestJson;
}

namespace engine {

  /// class TestJson - 
  class TestJson {
    // Attributes
  public:
    std::string nom;
    int age;
    // Operations
  public:
    TestJson (std::string nom, int age);
    void serialize (Json::Value& out) const;
    TestJson* deserialize (const Json::Value& in);
    // Setters and Getters
  };

};

#endif
