// Generated by dia2code
#ifndef SERVER__PLAYER__H
#define SERVER__PLAYER__H

#include <string>

namespace server {

  /// class Player - 
  class Player {
    // Attributes
  public:
    std::string color;
    std::string name;
    // Operations
  public:
    Player (std::string color, std::string name);
    // Setters and Getters
  };

};

#endif
