// Generated by dia2code
#ifndef __ENGINE__H
#define __ENGINE__H

#include "engine/Command.h"
#include "engine/CommandTypeId.h"
#include "engine/MoveCharCommand.h"
#include "engine/OrientationCommand.h"
#include "engine/HandleLifesCommand.h"
#include "engine/Engine.h"
#endif
