// Generated by dia2code
#ifndef __ENGINE__H
#define __ENGINE__H

#include "engine/CommandTypeId.h"
#include "engine/ActionTypeId.h"
#include "engine/Action.h"
#include "engine/Engine.h"
#include "engine/Command.h"
#include "engine/MoveCharCommand.h"
#include "engine/HandleLifesCommand.h"
#include "engine/LoadCommand.h"
#include "engine/ShootCommand.h"
#include "engine/MoveCharAction.h"
#include "engine/LifeAction.h"
#include "engine/KillCharAction.h"
#include "engine/ShootAction.h"
#include "engine/TestJson.h"
#endif
