// Generated by dia2code
#ifndef __ENGINE__H
#define __ENGINE__H

#include "engine/CommandTypeId.h"
#include "engine/Engine.h"
#include "engine/Command.h"
#include "engine/MoveCharCommand.h"
#include "engine/OrientationCommand.h"
#include "engine/HandleLifesCommand.h"
#include "engine/HandleImpactCommand.h"
#include "engine/JumpCommand.h"
#include "engine/ShootCommand.h"
#endif
