// Generated by dia2code
#ifndef __STATE__H
#define __STATE__H

#include "state/TypeId.h"
#include "state/Element.h"
#include "state/MobileElement.h"
#include "state/StaticElement.h"
#include "state/FloorTypeId.h"
#include "state/Floor.h"
#include "state/SpaceTypeId.h"
#include "state/Space.h"
#include "state/Personnage.h"
#include "state/ElementTab.h"
#include "state/State.h"
#include "state/Status.h"
#include "state/Direction.h"
<<<<<<< HEAD
#include "state/ElementAlloc.h"
=======
>>>>>>> e544559d0c95c33751e12a9c1149f2a9c648493e
#endif
